# Generated by Django 6.0 on 2025-12-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attCountry', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attCity', models.CharField(max_length=60)),
                ('attCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.country')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(verbose_name=150)),
                ('openingHours', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('attImage', models.ImageField(upload_to='')),
                ('attCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.country')),
            ],
        ),
    ]
