# Generated by Django 6.0 on 2025-12-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.city'),
        ),
    ]
