# Generated by Django 6.0 on 2025-12-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_attraction_attcity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
