# Generated by Django 6.0 on 2025-12-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_alter_city_options_alter_country_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='attCity',
            new_name='attractionCity',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='attImage',
            new_name='attractionImage',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='attCity',
            new_name='attractionCity',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='attCountry',
            new_name='attractionCountry',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='attCountry',
            new_name='attractionCountry',
        ),
    ]
