# Generated by Django 6.0 on 2025-12-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_rename_attcity_attraction_attractioncity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
