# Generated by Django 6.0 on 2025-12-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_alter_attraction_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
