# Generated by Django 6.0 on 2025-12-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_alter_attraction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='rate1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rate1_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rate2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rate2_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rate3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rate3_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rate4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rate4_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rate5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rateO_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attractionImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
