# Generated by Django 6.0 on 2025-12-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_attraction_rate1_attraction_rate1_5_attraction_rate2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='rate1',
            new_name='rate10',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rate1_5',
            new_name='rate15',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rate2',
            new_name='rate20',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rate2_5',
            new_name='rate25',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rate3',
            new_name='rate30',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rate3_5',
            new_name='rate35',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rate4',
            new_name='rate40',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rate4_5',
            new_name='rate45',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rate5',
            new_name='rate50',
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='rateO_5',
            new_name='rateO5',
        ),
    ]
