# Generated by Django 6.0 on 2025-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_rename_rate1_attraction_rate10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='rateO5',
            new_name='rate05',
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attractionImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
