# Generated by Django 6.0 on 2025-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_rename_rateo5_attraction_rate05_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.CharField(max_length=750),
        ),
    ]
